movement_core:
  diagram_variables:
    m1:
      - 0
      - 0
      - 0
    a1:
      - 0.0676
      - 0
      - 0
    a2:
      - 0.09237
      - 0
      - 0
    a3:
      - 0.22524
      - 0
      - 0
    software_angle1: 0.0
    software_angle2: 17.5
    software_angle3: 40.7
    hardware_angle1: 0.0
    hardware_angle2: 0.0
    hardware_angle3: 0.0